<?php

namespace App\Http\Controllers;

use App\Query;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        return view("admin/index", [
            "services" => Query::SERVICES
        ]);
    }

    public function __call($method, $parameters)
    {
        parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }
}
